"""'修改身份证长度bug'

Revision ID: b07d3696c53b
Revises: 
Create Date: 2019-05-12 01:07:05.465894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b07d3696c53b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_address', 'abc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('abc', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
