"""'增加支付宝订单号字段'

Revision ID: df62e2036b52
Revises: ad5211fe1bb5
Create Date: 2019-05-16 18:48:38.000973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df62e2036b52'
down_revision = 'ad5211fe1bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('trade_no', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_info', 'trade_no')
    # ### end Alembic commands ###
